"""Update job model with comprehensive fields

Revision ID: 6eab90937859
Revises: e3477339e9b7
Create Date: 2025-08-31 11:05:15.016824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6eab90937859'
down_revision: Union[str, None] = 'e3477339e9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_title', sa.String(length=255), nullable=False))
    op.add_column('jobs', sa.Column('company_name', sa.String(length=255), nullable=False))
    op.add_column('jobs', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('employment_type', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('work_mode', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('experience_required', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('education_required', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('skills_required', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('salary_type', sa.String(length=20), nullable=True))
    op.add_column('jobs', sa.Column('job_summary', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('roles_responsibilities', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('key_requirements', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('how_to_apply', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('number_of_openings', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('hiring_manager', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('recruiter_contact', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('job_status', sa.String(length=20), nullable=True))
    op.add_column('jobs', sa.Column('visibility', sa.String(length=20), nullable=True))
    op.add_column('jobs', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('posted_by', sa.Integer(), nullable=False))
    op.drop_index('ix_jobs_title', table_name='jobs')
    op.create_index(op.f('ix_jobs_job_title'), 'jobs', ['job_title'], unique=False)
    op.drop_constraint('jobs_ibfk_1', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'users', ['posted_by'], ['id'])
    op.drop_column('jobs', 'experience_level')
    op.drop_column('jobs', 'company_id')
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'requirements')
    op.drop_column('jobs', 'title')
    op.drop_column('jobs', 'is_remote')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'job_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_type', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('jobs', sa.Column('location', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('jobs', sa.Column('is_remote', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('title', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('jobs', sa.Column('requirements', mysql.TEXT(), nullable=True))
    op.add_column('jobs', sa.Column('description', mysql.TEXT(), nullable=False))
    op.add_column('jobs', sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('experience_level', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_ibfk_1', 'jobs', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_jobs_job_title'), table_name='jobs')
    op.create_index('ix_jobs_title', 'jobs', ['title'], unique=False)
    op.drop_column('jobs', 'posted_by')
    op.drop_column('jobs', 'tags')
    op.drop_column('jobs', 'visibility')
    op.drop_column('jobs', 'job_status')
    op.drop_column('jobs', 'recruiter_contact')
    op.drop_column('jobs', 'hiring_manager')
    op.drop_column('jobs', 'number_of_openings')
    op.drop_column('jobs', 'how_to_apply')
    op.drop_column('jobs', 'application_deadline')
    op.drop_column('jobs', 'key_requirements')
    op.drop_column('jobs', 'roles_responsibilities')
    op.drop_column('jobs', 'job_summary')
    op.drop_column('jobs', 'salary_type')
    op.drop_column('jobs', 'skills_required')
    op.drop_column('jobs', 'education_required')
    op.drop_column('jobs', 'experience_required')
    op.drop_column('jobs', 'country')
    op.drop_column('jobs', 'state')
    op.drop_column('jobs', 'city')
    op.drop_column('jobs', 'work_mode')
    op.drop_column('jobs', 'employment_type')
    op.drop_column('jobs', 'industry')
    op.drop_column('jobs', 'company_name')
    op.drop_column('jobs', 'job_title')
    # ### end Alembic commands ###
