"""Add password reset OTP fields

Revision ID: e3477339e9b7
Revises: 521823332571
Create Date: 2025-08-30 21:39:01.500858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3477339e9b7'
down_revision: Union[str, None] = '521823332571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('password_reset_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_otp_expires_at')
    op.drop_column('users', 'password_reset_otp')
    # ### end Alembic commands ###
